### ISSUE TITLE
Error while building i3status-rust

### ISSUE THREAD

**Issue by concatime** [polyzen/pkgbuilds#2]
Hi. It seems that `pkg-config` should be a dependency of this package.
![error](https://user-images.githubusercontent.com/26262387/32817514-31c494e0-c98c-11e7-9e55-91ae65a4f52a.png)
Thank you ;)

**Comment by polyzen** [comment]
`pkg-config` is to be installed as part of the `base-devel` group: https://wiki.archlinux.org/index.php/Arch_User_Repository#Prerequisites
